.PHONY: dist clean sync sync-check cursor opencode openclaw codex validate install-hooks uninstall-hooks bump release test-cli

# ============================================================================
# Sync — Generate .claude/, .opencode/, .cursor/rules/ from .buildwright/ (canonical)
# Source of truth: .buildwright/ → .claude/ + .opencode/ + .cursor/rules/ + AGENTS.md + dist/
# ============================================================================

sync:
	@chmod +x scripts/sync-agents.sh
	@scripts/sync-agents.sh

sync-check:
	@chmod +x scripts/sync-agents.sh
	@scripts/sync-agents.sh --check

# ============================================================================
# Package for distribution
# ============================================================================

# ClawHub — upload dist/buildwright/ folder to https://clawhub.ai/upload
dist: sync
	@echo "dist/buildwright/ ready — upload this folder to ClawHub"

# Cursor — print setup instructions (rules generated by make sync)
cursor: sync
	@echo "Cursor rules generated at .cursor/rules/"
	@echo "Open this project in Cursor — rules are applied automatically."
	@echo "Settings > Rules shows steering rules as 'Always' and commands/agents/claws as 'Intelligent'."

# OpenCode — install skill to user global config
opencode: sync
	@mkdir -p ~/.config/opencode/skills/buildwright
	@cp SKILL.md ~/.config/opencode/skills/buildwright/SKILL.md
	@echo "Installed to ~/.config/opencode/skills/buildwright/"

# OpenClaw — install skill to user skills directory
openclaw: sync
	@mkdir -p ~/.openclaw/skills/buildwright
	@cp SKILL.md ~/.openclaw/skills/buildwright/SKILL.md
	@echo "Installed to ~/.openclaw/skills/buildwright/"

# Codex CLI — install skills for native skill discovery
codex: sync
	@mkdir -p ~/.agents/skills
	@ln -sfn $(PWD)/skills ~/.agents/skills/buildwright
	@echo "Installed to ~/.agents/skills/buildwright"
	@echo "Restart Codex to discover Buildwright skills."

# ============================================================================
# Validate SKILL.md against Agent Skills spec (agentskills.io)
# ============================================================================

validate:
	@chmod +x scripts/validate-skill.sh
	@scripts/validate-skill.sh SKILL.md

# ============================================================================
# Git Hooks — keep .buildwright/ ↔ generated files in sync automatically
# ============================================================================

install-hooks:
	@chmod +x scripts/install-hooks.sh
	@scripts/install-hooks.sh

uninstall-hooks:
	@rm -f .git/hooks/pre-commit .git/hooks/post-merge .git/hooks/post-checkout
	@echo "Buildwright hooks removed."

# ============================================================================
# Clean
# ============================================================================

bump: ## Bump version files only (no git ops): make bump [BUMP=patch|minor|major]
	@chmod +x scripts/bump-version.sh
	@scripts/bump-version.sh $(or $(BUMP),patch)

release: ## Full release: bump, commit, tag, push, GitHub release, npm publish: make release [BUMP=patch|minor|major]
	@chmod +x scripts/release.sh
	@scripts/release.sh $(or $(BUMP),patch)

test-cli: ## Pack and install CLI globally for local testing
	@echo "Packing cli/..."
	@cd cli && npm pack
	@TARBALL=$$(ls cli/buildwright-*.tgz | tail -1) && \
	  npm install -g "./$$TARBALL" && \
	  rm -f "$$TARBALL"
	@echo ""
	@echo "✓ buildwright installed globally from local pack"
	@echo "  Test it: cd /tmp && mkdir test-bw && cd test-bw && buildwright init"
	@echo "  Uninstall: npm uninstall -g buildwright"

clean:
	rm -rf dist/
