.PHONY: dist clean sync sync-check cursor opencode openclaw validate

# ============================================================================
# Sync — Generate .claude/, .opencode/, .cursor/rules/ from .buildwright/ (canonical)
# Source of truth: .buildwright/ → .claude/ + .opencode/ + .cursor/rules/ + AGENTS.md + dist/
# ============================================================================

sync:
	@chmod +x scripts/sync-agents.sh
	@scripts/sync-agents.sh

sync-check:
	@chmod +x scripts/sync-agents.sh
	@scripts/sync-agents.sh --check

# ============================================================================
# Package for distribution
# ============================================================================

# ClawHub — upload dist/buildwright/ folder to https://clawhub.ai/upload
dist: sync
	@echo "dist/buildwright/ ready — upload this folder to ClawHub"

# Cursor — print setup instructions (rules generated by make sync)
cursor: sync
	@echo "Cursor rules generated at .cursor/rules/"
	@echo "Open this project in Cursor — rules are applied automatically."
	@echo "Settings > Rules shows steering rules as 'Always' and commands/agents/claws as 'Intelligent'."

# OpenCode — install skill to user global config
opencode: sync
	@mkdir -p ~/.config/opencode/skills/buildwright
	@cp SKILL.md ~/.config/opencode/skills/buildwright/SKILL.md
	@echo "Installed to ~/.config/opencode/skills/buildwright/"

# OpenClaw — install skill to user skills directory
openclaw: sync
	@mkdir -p ~/.openclaw/skills/buildwright
	@cp SKILL.md ~/.openclaw/skills/buildwright/SKILL.md
	@echo "Installed to ~/.openclaw/skills/buildwright/"

# ============================================================================
# Validate SKILL.md against Agent Skills spec (agentskills.io)
# ============================================================================

validate:
	@chmod +x scripts/validate-skill.sh
	@scripts/validate-skill.sh SKILL.md

# ============================================================================
# Clean
# ============================================================================

clean:
	rm -rf dist/
